cc_library(
    name = "tensorrt_headers",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "tensorrt",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "build_defs_bzl",
    srcs = ["build_defs.bzl"],
    visibility = ["//visibility:public"],
)
