name: s2t-env-py311
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - absl-py==2.4.0
    - altgraph==0.17.5
    - astunparse==1.6.3
    - certifi==2026.2.25
    - charset-normalizer==3.4.5
    - delocate==0.13.0
    - flatbuffers==25.12.19
    - gast==0.7.0
    - google-pasta==0.2.0
    - googleapis-common-protos==1.72.0
    - grpcio==1.78.0
    - h5py==3.16.0
    - idna==3.11
    - keras==3.13.2
    - libclang==18.1.1
    - macholib==1.16.4
    - markdown==3.10.2
    - markdown-it-py==4.0.0
    - markupsafe==3.0.3
    - mdurl==0.1.2
    - ml-dtypes==0.4.1
    - namex==0.1.0
    - numpy==1.26.4
    - opt-einsum==3.4.0
    - optree==0.19.0
    - protobuf==4.25.8
    - pyarrow==10.0.1
    - pygments==2.19.2
    - requests==2.32.5
    - rich==14.3.3
    - six==1.17.0
    - tensorboard==2.18.1
    - tensorboard-data-server==0.7.2
    - tensorflow==2.18.1
    - tensorflow-io-gcs-filesystem==0.37.1
    - tensorflow-metadata==1.17.3
    - termcolor==3.3.0
    - typing-extensions==4.15.0
    - urllib3==2.6.3
    - werkzeug==3.1.6
    - wrapt==2.1.2
