cc_library(
    name = "nccl_headers",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "nccl_config",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "nccl",
    visibility = ["//visibility:public"],
)
