def ios_application(name, **kwargs): pass
def ios_app_clip(name, **kwargs): pass
def ios_dynamic_framework(name, **kwargs): pass
def ios_extension(name, **kwargs): pass
def ios_framework(name, **kwargs): pass
def ios_imessage_application(name, **kwargs): pass
def ios_sticker_pack_extension(name, **kwargs): pass
def ios_imessage_extension(name, **kwargs): pass
def ios_static_framework(name, **kwargs): pass
def ios_unit_test(name, **kwargs): pass
def ios_ui_test(name, **kwargs): pass
def ios_unit_test_suite(name, **kwargs): pass
def ios_ui_test_suite(name, **kwargs): pass
def ios_build_test(name, **kwargs): pass
