name: Reusable action which builds struct2tensor

inputs:
  python-version:
    description: 'Python version'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install `cibuildwheel`
      shell: bash
      run: |
        pip install cibuildwheel

    - name: Build the package for Python ${{ inputs.python-version }}
      shell: bash
      run: |
        cibuildwheel --output-dir dist

    - name: Upload wheel artifact for Python ${{ inputs.python-version }}
      uses: actions/upload-artifact@v4
      with:
        name: ml-metadata-wheel-py${{ inputs.python-version }}
        path: dist/*.whl
        if-no-files-found: error
