name: deploy-docs
on:
  workflow_dispatch:
  pull_request:
  push:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            setup.py

      - name: Save time for cache for mkdocs
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Caching
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install Dependencies
        run: pip install mkdocs mkdocs-material mkdocstrings[python] griffe-inherited-docstrings mkdocs-autorefs mkdocs-jupyter mkdocs-caption markdown-grid-tables

      - name: Deploy to GitHub Pages
        if: (github.event_name != 'pull_request')
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          mkdocs gh-deploy --force

      - name: Build docs to check for errors
        if: (github.event_name == 'pull_request')
        run: |
          mkdocs build
